### ISSUE TITLE
error editing config.json

### ISSUE THREAD

**Issue by deadcode0815** [datawhores/ofscraper#17]
Editing config.jsob

`PS F:\OF> ofscraper
? What would you like to do? Edit config.json file
? What would you like your main profile to be? main_profile
? Where would you like to set as the root save downloaded directory? C:\Users\ofscraper\Data\ofscraper
? File size limit (enter a value in bytes)
Leave empty string for no limit:
? What format do you want for download directories {model_username}/{responsetype}/{mediatype}/
? What format do you want for downloaded files {filename}.{ext}
Traceback (most recent call last):
  File "C:\Users\ofscraper\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ofscraper\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ofscraper\AppData\Local\Programs\Python\Python310\Scripts\ofscraper.exe\__main__.py", line 7, in <module>
  File "C:\Users\ofscraper\AppData\Local\Programs\Python\Python310\lib\site-packages\src\scraper.py", line 562, in main
    process_prompts()
  File "C:\Users\ofscraper\AppData\Local\Programs\Python\Python310\lib\site-packages\src\scraper.py", line 250, in process_prompts
    config.edit_config()
  File "C:\Users\ofscraper\AppData\Local\Programs\Python\Python310\lib\site-packages\src\utils\config.py", line 127, in edit_config
    'config': config_prompt(config['config'])
  File "C:\Users\ofscraper\AppData\Local\Programs\Python\Python310\lib\site-packages\src\utils\prompts.py", line 405, in config_prompt
    answers = prompt(questions)
  File "C:\Users\ofscraper\AppData\Local\Programs\Python\Python310\lib\site-packages\InquirerPy\resolver.py", line 213, in prompt
    result[question_name] = question_mapping[question_type](
  File "C:\Users\ofscraper\AppData\Local\Programs\Python\Python310\lib\site-packages\InquirerPy\prompts\input.py", line 131, in __init__
    raise InvalidArgument(
InquirerPy.exceptions.InvalidArgument: InputPrompt argument 'default' should be type of str
PS F:\OF>`

**Comment by datawhores** [comment]
have you been able to use this script
