### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by CannotTouch** [datawhores/ofscraper#28]
I have just installed it with the `pip install ofscraper` and at the first run i received this error

E:\ofscraper-main>ofscraper
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\asd\AppData\Local\Programs\Python\Python311\Scripts\ofscraper.exe\__main__.py", line 4, in <module>
  File "C:\Users\asd\AppData\Local\Programs\Python\Python311\Lib\site-packages\src\scraper.py", line 132
    reexcludedBittern8turn output
                           ^^^^^^
SyntaxError: invalid syntax

**Comment by datawhores** [comment]
I'll push a fix for this very soon.
Theirs some externus text

**Comment by CannotTouch** [comment]
Thanks, but i still have the same error. Maybe I didn't understand if you have yet pushed it or not.

**Comment by datawhores** [comment]
Are you on 1.87?

**Comment by CannotTouch** [comment]
sorry is a bit changed the error:

E:\ofscraper-main>ofscraper
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Seaquake\AppData\Local\Programs\Python\Python311\Scripts\ofscraper.exe\__main__.py", line 4, in <module>
  File "C:\Users\Seaquake\AppData\Local\Programs\Python\Python311\Lib\site-packages\src\scraper.py", line 132
    reexcludedBittern8turn output
                           ^^^^^^
SyntaxError: invalid syntax

**Comment by datawhores** [comment]
Are you on 1.87?
Edit it should work if you do
Pip install ofscraper==1.87

**Comment by datawhores** [comment]
I did a fresh install on a new computer and wasn't able to recreate the error 

Can you try to uninstall and
Do pip install ofscraper==1.87

I can do a more through look in a bit if it doesn't work.

**Comment by CannotTouch** [comment]
ok it works now. thanks for the support :)
