### ISSUE TITLE
Getting error in scraper.py after the --dupe fix

### ISSUE THREAD

**Issue by cornerdebug** [datawhores/ofscraper#7]
Tried a fresh install in a Python venv and getting the following error:

```
Traceback (most recent call last):
  File "/onlyfans/venv/bin/ofscraper", line 5, in <module>
    from src.scraper import main
  File "/onlyfans/venv/lib/python3.10/site-packages/src/scraper.py", line 31, in <module>
    from .api import init, highlights, me, messages, posts, profile, subscriptions, paid
  File "/onlyfans/venv/lib/python3.10/site-packages/src/api/messages.py", line 20, in <module>
    from ..db.operations import read_messages_response
  File "/onlyfans/venv/lib/python3.10/site-packages/src/db/operations.py", line 24, in <module>
    from ..utils.paths import createDir,databasePathHelper,messageResponsePathHelper,timelineResponsePathHelper,\
  File "/onlyfans/venv/lib/python3.10/site-packages/src/utils/paths.py", line 14, in <module>
    config = read_config()['config']
  File "/onlyfans/venv/lib/python3.10/site-packages/src/utils/config.py", line 28, in read_config
    config = json.load(f)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Worked fine with the --dupe workaround yesterday, but been getting the error since the fix.

**Comment by excludedBittern8** [comment]
Their is an error in the config file
what system are you on it should be in your home directory in the .config/ofscraper folder

`{
    "config": {
        "main_profile": "main_profile",
        "save_location": "/root/ofscraper/Data",
        "file_size_limit": "",
        "dir_format": "{model_username}/{responsetype}/{mediatype}",
        "file_format": "{filename}.{ext}",
        "textlength": "0",
        "date": "{configpath}/{profile}/.data/{username}_{model_id}",
        "metadata": "{configpath}/{profile}/.data/{username}_{model_id}"
    }
}
`

**Comment by excludedBittern8** [comment]
I added a feature to detect if config.json is in correct, and offer the chance to fix it in the latest commit. 
You can manually edit or just reset it to the default settings

```
 config': {
            "mainProfile": mainProfile,
            'save_location': str(pathlib.Path.home() /'Data/ofscraper'),
            'file_size_limit': '',
            'dir_format':'{model_username}/{responsetype}/{mediatype}/',
            'file_format': '{filename}.{ext}',
            'textlength':0,
            'date':"MM-DD-YYYY",
            'metadata':"{configpath}/{profile}/.data/{username}_{model_id}"
        }
```
